### ISSUE TITLE
0.1.0?

### ISSUE THREAD

**Issue by NeQuissimus** [zio/zio-shield#23]
Is this far enough along you could release a v0.1.0?
I'd rather not fetch a snapshot :)

Thanks!

**Comment by vovapolu** [comment]
Yeah, no problem :) Could we also publish it under the zio organization, not under my custom `com.github.vovapolu`? I need some help with it.

**Comment by NeQuissimus** [comment]
For sure.
Take a look at `zio-kafka`, it should have everything you need in its `.circleci/config.yaml`.
Just adjust the `groupId` in your `build.sbt`

**Comment by vovapolu** [comment]
@NeQuissimus 
Are `PGP_PUBLIC` and `PGP_SECRET` defined in the whole `zio` github organization? If not where I can get them or set up?

**Comment by NeQuissimus** [comment]
`context: Sonatype` will give them to you

**Comment by vovapolu** [comment]
@NeQuissimus Sorry for the delay :) I've set up circleci configuration in the `zio-shield` repository, but now I can't see any circleci jobs, probably because I'm not in the `zio` orgranization. Could you help me?

**Comment by NeQuissimus** [comment]
I have enabled this repo in CircleCI

**Comment by vovapolu** [comment]
@NeQuissimus Thanks! I've released `zio-shield` under `dev.zio` org. 

One last question: does `zio` have custom Sonatype repository? Something like bintray repository (for example, I have `bintray:vovapolu` repository). I need one to publish custom metals build with integrated `zio-shield`.

**Comment by NeQuissimus** [comment]
No, all the ZIO stuff goes through Sonatype Releases into Maven Central
